---
system_monitors_configs_location: 'stage'
system_monitors_deployed:

aws_elb_monitors_configs_location: 'application'
aws_elb_monitors_list: 
  - test
aws_elb_monitors_configs: 
  test:
    a: 1
aws_elb_monitors_deployed: